This is an example notebook on the Markov network simulator-model. The model is constructed in ELFI-format. 

In [1]:
from functools import partial
import itertools

import elfi
import numpy as np
import scipy.stats as ss
import markov_network as mn

In [2]:
model = mn.get_model()

[[0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]
(7, 1)
GMN simulate
(1, 7)
(1, 7)
(1, 7)
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  2.  2.  2.
   2.  2.  2.  2.  2.  2.  3.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  5.
   5.  5.  5.  5.  6.  6.  6.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.
   9.  9.  9. 10. 10. 10. 12. 12. 12. 13.]]
(1, 100)
{'name': 'd'}


In [3]:
# ?model.generate
res = model.generate(batch_size=2,outputs=['GMN','S','d'])

sumstats
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  2.  2.  2.
   2.  2.  2.  2.  2.  2.  3.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  5.
   5.  5.  5.  5.  6.  6.  6.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.
   9.  9.  9. 10. 10. 10. 12. 12. 12. 13.]]
16
(1, 100)
1
[41 12 10  2 11  6  4  1 12  4  4  1  4  2  1  1]
(16,)
GMN simulate
(2, 7)
(2, 7)
(2, 7)
[[ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  2.  3.  3.  3.  3.  3.  3.  3.  4.  4.  5.  5.  5.  5.  5.  5.  5.
   5.  5.  6.  6.  7.  7.  7.  7.  7.  9.  9.  9.  9.  9.  9.  9.  9.  9.
   9.  9.  9.  9.  9.  9.  9.  9.  9. 11. 11. 11. 11. 11. 11. 11. 11. 11.
  11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11.
  11. 11. 11. 11. 11. 11. 11. 11. 13. 15.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1

In [4]:
res

{'S': array([[-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
         12., 13., 14.],
        [14., 11.,  0.,  1., 38.,  9.,  5.,  4.,  2.,  0.,  4.,  0.,  6.,
          0.,  5.,  1.]]),
 'd': array([51.80733539, 41.27953488]),
 'GMN': array([[ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.,  1.,  1.,  1.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,
          3.,  4.,  4.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  6.,
          6.,  7.,  7.,  7.,  7.,  7.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,
          9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9., 11., 11.,
         11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11.,
         11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11.,
         11., 11., 11., 11., 11., 11., 11., 13., 15.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  3.,
          4.,  4.,  4.,  4

In [13]:
res['GMN'].shape

(100, 4)

In [4]:
dag, node_ordering = mn.ug_to_dag(ug)
print(ug)
print(dag)
print(node_ordering)

[[0. 1. 1. 1.]
 [1. 0. 1. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]]
[[0. 1. 1. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 1 2 3]


In [6]:
para_val_true

array([[ -2.31976435],
       [  0.26793721],
       [ -1.96695206],
       [ -8.51791329],
       [  1.32422672],
       [-12.35055686],
       [-14.29780551],
       [ 14.72327849],
       [ 22.66087623],
       [-19.13751914]])

In [7]:
para_mat_true, para_val_true = mn.mn_sample_para(ug, 10, 10)
print(para_mat_true)

[[False False False False]
 [False False False  True]
 [False False  True False]
 [False  True False False]
 [False  True  True False]
 [ True False False False]
 [ True False False  True]
 [ True False  True False]
 [ True  True False False]
 [ True  True  True False]]


In [8]:
dag

array([[0., 1., 1., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
dag, node_ordering = mn.ug_to_dag(ug)

In [10]:
print(ug)

[[0. 1. 1. 1.]
 [1. 0. 1. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]]


AttributeError: 'numpy.ndarray' object has no attribute 'len'

In [36]:
node = 3
par = np.where(dag[:, node] == 1)[0]
print(par.size)

1


In [3]:
?np.tile

Signature: np.tile(A, reps)
Docstring:
Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat e

In [23]:
ss.multinomial.rvs([10,10], np.array([[0.1, 0.2, 0.7],[0.3, 0.3, 0.4]]), size=2, random_state=None)

TypeError: only size-1 arrays can be converted to Python scalars

In [25]:
ss.beta.rvs(0.1, 0.1, size=5).shape

(5,)

In [4]:
z = (array([0.31122762, 0.35690599]), array([0.22026763, 0.99994579]), array([0.99549973, 0.53046661]), array([4.05215817e-01, 1.61070359e-06]), array([0.71567369, 0.99999985]), array([0.2826452 , 0.32809147]), array([0.94246955, 0.05651268]))

NameError: name 'array' is not defined

In [18]:
a = np.array((0, 1))
b = np.array((2, 1))
c = np.array((3, 4))
d = np.column_stack((a,b,c))

In [19]:
d

array([[0, 2, 3],
       [1, 1, 4]])

In [20]:
e = np.atleast_2d(np.arange((5)))
print(e.shape)
tmp0, tmp1 = np.apply_along_axis(np.unique, 1, np.column_stack((d, e[np.zeros(2).astype(int),:])), return_counts=True)
# tmp, counts = np.unique(np.column_stack((d, e[np.zeros(2).astype(int),:])), axis=1, return_counts=True)
print(tmp0)
print(tmp1)
# print(counts)

(1, 5)
[[0 1 2 3 4]
 [2 1 2 2 1]]
[[0 1 2 3 4]
 [1 3 1 1 2]]


In [13]:
?np.apply_along_axis

Signature: np.apply_along_axis(func1d, axis, arr, *args, **kwargs)
Docstring:
Apply a function to 1-D slices along the given axis.

Execute `func1d(a, *args)` where `func1d` operates on 1-D arrays and `a`
is a 1-D slice of `arr` along `axis`.

This is equivalent to (but faster than) the following use of `ndindex` and
`s_`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of indices::

    Ni, Nk = a.shape[:axis], a.shape[axis+1:]
    for ii in ndindex(Ni):
        for kk in ndindex(Nk):
            f = func1d(arr[ii + s_[:,] + kk])
            Nj = f.shape
            for jj in ndindex(Nj):
                out[ii + jj + kk] = f[jj]

Equivalently, eliminating the inner loop, this can be expressed as::

    Ni, Nk = a.shape[:axis], a.shape[axis+1:]
    for ii in ndindex(Ni):
        for kk in ndindex(Nk):
            out[ii + s_[...,] + kk] = func1d(arr[ii + s_[:,] + kk])

Parameters
----------
func1d : function (M,) -> (Nj...)
    This function should accept 1-D arrays. It is ap

In [9]:
?np.unique

Signature:
np.unique(
    ar,
    return_index=False,
    return_inverse=False,
    return_counts=False,
    axis=None,
)
Docstring:
Find the unique elements of an array.

Returns the sorted unique elements of an array. There are three optional
outputs in addition to the unique elements:

* the indices of the input array that give the unique values
* the indices of the unique array that reconstruct the input array
* the number of times each unique value comes up in the input array

Parameters
----------
ar : array_like
    Input array. Unless `axis` is specified, this will be flattened if it
    is not already 1-D.
return_index : bool, optional
    If True, also return the indices of `ar` (along the specified axis,
    if provided, or in the flattened array) that result in the unique array.
return_inverse : bool, optional
    If True, also return the indices of the unique array (for the specified
    axis, if provided) that can be used to reconstruct `ar`.
return_counts : bool, optiona