In [13]:
"""Example implementation of the 2nd order Moving Average (MA2) model."""

from functools import partial
import itertools

import elfi
import numpy as np
import scipy.stats as ss


In [219]:
ug = np.zeros((4, 4))
ug[0,1:4] = 1
# ug = np.max(ug, ug.T)
ug = ug + ug.T
ug[1,2] = 1
ug[2,1] = 1

# Generate values from the prior as the ground truth
para_mat_true, para_val_true = mn_sample_para(ug, 1, 5)
print(para_mat_true)
print(para_val_true)
# Generate observed data

lex_ordering
[0 1 2 3]
[3 2 1 0]
[[0. 1. 1. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 1 2 3]
[[0. 1. 1. 1.]
 [1. 0. 1. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]]
[[False False False False]
 [False False False  True]
 [False False  True False]
 [False  True False False]
 [False  True  True False]
 [ True False False False]
 [ True False False  True]
 [ True False  True False]
 [ True  True False False]
 [ True  True  True False]]
[[-1.41466920e+01]
 [-7.07190525e+00]
 [ 1.34812873e+01]
 [ 2.08196153e+00]
 [-1.34812873e+01]
 [ 1.34232397e+01]
 [-8.88178420e-16]
 [-1.34812873e+01]
 [-2.20918730e+01]
 [ 2.20916895e+01]]
