This is an example notebook on the Markov network simulator-model. The model is constructed in ELFI-format. 

In [1]:
from functools import partial
import itertools

import elfi
import numpy as np
import scipy.stats as ss
import markov_network as mn

In [9]:
ug = np.zeros((4, 4))
ug[0,1:4] = 1
ug[1,2] = 1
# ug = np.max(ug, ug.T)
ug = ug + ug.T

# Generate values from the prior as the ground truth
para_mat_true, para_val_true = mn.mn_sample_para(ug, 1, 5)
# Generate observed data
obs_data = mn.mn_generate_data(para_mat_true, para_val_true, 100, 0)


How does this work??
[[ True  True  True  True]
 [ True  True  True False]
 [ True  True False  True]
 [ True  True False False]
 [ True False  True  True]
 [ True False  True False]
 [ True False False  True]
 [ True False False False]
 [False  True  True  True]
 [False  True  True False]
 [False  True False  True]
 [False  True False False]
 [False False  True  True]
 [False False  True False]
 [False False False  True]
 [False False False False]]
[[5.72126883e-06]
 [2.83174506e-07]
 [4.23507456e-06]
 [2.09615241e-07]
 [4.67515012e-01]
 [2.31396804e-02]
 [4.67515012e-01]
 [2.31396804e-02]
 [1.03351804e-05]
 [5.11540306e-07]
 [1.03351804e-05]
 [5.11540306e-07]
 [1.14053256e-05]
 [5.64507200e-07]
 [4.85292466e-01]
 [2.40195765e-02]]
[[False False False False]
 [False False False  True]
 [False False  True False]
 [False  True False False]
 [False  True  True False]
 [ True False False False]
 [ True False False  True]
 [ True False  True False]
 [ True  True False False]
 [ True  True 

ValueError: pvals < 0, pvals > 1 or pvals contains NaNs

In [6]:
print(obs_data)
mn.mn_calculate_jsd(~obs_data, para_mat_true, obs_data)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]
 

0.40346541464179136

In [10]:
dag, node_ordering = mn.ug_to_dag(ug)
print(ug)
print(dag)
print(node_ordering)

[[0. 1. 1. 1.]
 [1. 0. 1. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]]
[[0. 1. 1. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 1 2 3]


In [5]:
ug

array([[0., 1., 1., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])